- lua/client/client_util.lua
- lua/core/engine.lua
- packages/standard/init.lua
- packages/standard_cards/init.lua
- qml/Pages/CardsOverview.qml
- qml/Pages/GeneralsOverview.qml
- qml/Pages/Lobby.qml
- qml/Pages/RoomElement/Photo.qml
- qml/main.qml
- src/ui/qmlbackend.cpp
- src/ui/qmlbackend.h
todo: make these pages singleton
> General & Cards overview

- README.md
- doc/dev/database.md
- lua/client/client.lua
- lua/client/client_util.lua
- lua/core/engine.lua
- lua/server/room.lua
- packages/standard/aux_skills.lua
- packages/standard/init.lua
- qml/Logic.js
- qml/Pages/Room.qml
- qml/Pages/RoomElement/Dashboard.qml
- qml/Pages/RoomLogic.js
询问发动主动技，以及派生出的：
- askForDiscard
- askForChoosePlayers
> askForUseActiveSkill

- lua/client/client.lua
- lua/core/card.lua
- lua/core/util.lua
- lua/server/room.lua
- packages/test/init.lua
- qml/Pages/Room.qml
- qml/Pages/RoomElement/AG.qml
- qml/Pages/RoomElement/PlayerCardBox.qml
- qml/Pages/RoomLogic.js
> Interaction

- lua/client/client.lua
- lua/client/client_util.lua
- lua/core/exppattern.lua
- lua/core/skill_type/active.lua
- lua/core/util.lua
- lua/server/ai/ai.lua
- lua/server/ai/random_ai.lua
- lua/server/gamelogic.lua
- lua/server/room.lua
- packages/standard/i18n/en_US.lua
- packages/standard_cards/init.lua
- packages/test/init.lua
- qml/Pages/RoomElement/Dashboard.qml
- qml/Pages/RoomElement/PlayerCardBox.qml
添加了弹出pile的UI支持
修复选牌框bug
修复事件相关的报错bug
> Expand pile

- .gitignore
- android/AndroidManifest.xml
- android/src/org/notify/FreeKill/Helper.java
- src/main.cpp
将工作目录调整到/sdcard/Android/data/xxx，方便玩家修改
对于三按钮导航的手机，自动隐藏三按钮
> Android enhancement

- lua/client/client.lua
- lua/client/i18n/zh_CN.lua
- lua/core/engine.lua
- lua/core/util.lua
- lua/server/gamelogic.lua
- lua/server/room.lua
- packages/maneuvering/init.lua
- qml/Config.qml
- qml/Pages/Lobby.qml
- qml/Pages/LobbyElement/CreateRoom.qml
- qml/Pages/LobbyElement/EditProfile.qml
- qml/Pages/LobbyElement/RoomGeneralSettings.qml
- qml/Pages/LobbyElement/RoomPackageSettings.qml
> Custom Packages When Creating Room

- lua/client/client.lua
- lua/client/i18n/zh_CN.lua
> move card log (WIP)

- lua/core/player.lua
- lua/server/events/hp.lua
- lua/server/room.lua
- lua/server/serverplayer.lua
- qml/Pages/RoomElement/CardItem.qml
- qml/Pages/RoomElement/GeneralCardItem.qml
- qml/Pages/RoomElement/SkillArea.qml
> Fix more bug

- lua/client/client_util.lua
- lua/client/i18n/zh_CN.lua
- lua/core/engine.lua
- lua/core/general.lua
- qml/Pages/RoomElement/Cheat/SameConvert.qml
- qml/Pages/RoomElement/ChooseGeneralBox.qml
- qml/Pages/RoomElement/GeneralCardItem.qml
> Same general

- lua/core/player.lua
> player_doc

- lua/server/events/death.lua
- lua/server/events/hp.lua
- lua/server/gamelogic.lua
- lua/server/room.lua
- lua/server/system_enum.lua
- packages/standard/aux_skills.lua
- packages/standard/game_rule.lua
- qml/Pages/RoomElement/Dashboard.qml
- qml/Pages/RoomElement/ViewPile.qml
> Modify process & UI component

- lua/client/client_util.lua
- lua/core/card.lua
- lua/core/player.lua
- lua/core/skill_type/trigger.lua
- lua/core/util.lua
- lua/server/events/init.lua
- lua/server/gameevent.lua
- lua/server/gamelogic.lua
- packages/maneuvering/init.lua
- qml/Pages/RoomElement/CardItem.qml
- qml/Pages/RoomElement/Cheat/PlayerDetail.qml
- qml/Pages/RoomElement/GraphicsBox.qml
- qml/Pages/RoomElement/Photo.qml
优化拖曳
牌局查看技能
狮子不给死人加血
GameEvent相关函数
觉醒技默认cost和锁定技一样
> Enhancement

- lua/client/client.lua
- lua/client/client_util.lua
- lua/core/engine.lua
- lua/core/skill_type/filter.lua
- lua/fk_ex.lua
- lua/server/room.lua
- packages/standard/aux_skills.lua
- packages/standard/i18n/zh_CN.lua
- qml/Pages/RoomElement/Dashboard.qml
禁止使用打出弃置
Fk.currentResponseReason
FilterSkill加player参数
> Card limitation

- lua/core/game_mode.lua
- lua/core/general.lua
- lua/core/skill.lua
> core_doc_20230412_0844

- qml/Logic.js
- qml/Pages/Danmaku.qml
- qml/Pages/Lobby.qml
- qml/Pages/Room.qml
- src/server/room.cpp
- src/server/server.cpp
- src/server/server.h
- src/server/shell.cpp
- src/server/shell.h
新增旁观者聊天栏兼公告栏
增加服务端广播消息功能
修复单机启动失败时被心跳包卡死机的情况
修复发配音时undefined
> Observer chat

- src/core/util.cpp
- src/core/util.h
- src/main.cpp
- src/server/server.cpp
- src/server/server.h
- src/server/shell.cpp
- src/server/shell.h
为Linux加了彩字
为服务端加个读配置的接口——不过我暂时想不出服务端有啥好配置的
> init server config

- lua/client/client_util.lua
- lua/client/i18n/zh_CN.lua
- lua/core/engine.lua
- lua/core/general.lua
- lua/core/skill.lua
- lua/core/skill_type/view_as.lua
- lua/fk_ex.lua
- lua/server/event.lua
- lua/server/events/death.lua
- lua/server/gamelogic.lua
- lua/server/room.lua
- lua/server/serverplayer.lua
- qml/Pages/Room.qml
- qml/Pages/RoomElement/Dashboard.qml
- qml/Pages/RoomElement/GeneralCardItem.qml
- 实现副势力概念，用于应对双势力机制；
- 完善神将及拥有副势力的武将开局选择势力的机制；
- 完成势力技概念；
- 实现ViewAsSkill在响应时对使用和打出的区分。
> Initial kingdom choosing

- lua/core/card.lua
- lua/server/events/usecard.lua
- packages/maneuvering/init.lua
- packages/standard/aux_skills.lua
- qml/Pages/Common/ChatBox.qml
- qml/Pages/Common/LogEdit.qml
- qml/Pages/RoomLogic.js
Card.Void, aux_skills, move card reason, clone card attackrange
> LogEdit, Card.Void, aux_skills

- lua/client/client.lua
- lua/client/client_util.lua
- lua/client/i18n/zh_CN.lua
- lua/core/engine.lua
- lua/server/room.lua
- qml/Config.qml
- qml/Pages/GeneralsOverview.qml
- qml/Pages/Lobby.qml
- qml/Pages/LobbyElement/RoomGeneralSettings.qml
> ban generals

- Fk/LobbyElement/RoomGeneralSettings.qml
- Fk/Logic.js
- Fk/Pages/Lobby.qml
- lang/zh_CN.ts
- lua/client/i18n/zh_CN.lua
- src/network/router.cpp
- src/server/server.cpp
> Password room

- lua/core/card.lua
- lua/core/engine.lua
- lua/core/general.lua
- lua/core/player.lua
- lua/core/skill.lua
> player_doc更新

- lua/client/client.lua
> 避免Heartbeat重置currentResponse

- Fk/Logic.js
- Fk/Pages/Logic.js
- Fk/Pages/RoomLogic.js
- lua/core/player.lua
- 替换大多数let为const
- 将一些双等号替换为三等号
- 距离计算追加“玩家自己与距离为0”设定，副作用是不显示自身距离
> JS修改+距离计算修改

- Fk/Pages/Room.qml
- Fk/Pages/RoomLogic.js
- Fk/RoomElement/Dashboard.qml
- lua/client/client_util.lua
- lua/core/skill_type/active.lua
- lua/core/skill_type/view_as.lua
- lua/fk_ex.lua
- lua/ui-util.lua
- packages/test/init.lua
- 给interaction喂nil或者空choices可以禁止出interaction小黑框
- 可以给主动技/视为技上prompt
- 装备的技能现在会独立显示在最下方
> 选择性删除Interaction等各种功能

- Fk/Cheat/FreeAssign.qml
- Fk/Common/ChatBox.qml
- Fk/ModMaker/ModInit.qml
- Fk/Pages/CardsOverview.qml
- Fk/Pages/GeneralsOverview.qml
- Fk/Pages/Lobby.qml
- Fk/Pages/ModesOverview.qml
- Fk/Pages/PackageManage.qml
- Fk/Pages/Room.qml
- Fk/Pages/RoomLogic.js
- Fk/ToastManager.qml
- lua/client/client_util.lua
> 武将搜索+bug fix

- lua/client/client.lua
- lua/client/client_util.lua
- lua/core/skill_type/target_mod.lua
- lua/core/skill_type/usable_skill.lua
- lua/fk_ex.lua
- lua/ui-util.lua
- packages/standard/aux_skills.lua
- packages/standard/init.lua
- packages/standard_cards/init.lua
- 重命名isUnlimited/unlimited，因为未正式上线所以无关紧要(?)
- 新增bypassDistancesCheck/bypass_distances，实现真正的无距离限制
- 修复早退导致的报错bug
> bypassDistancesCheck + bugfix

- Fk/ModMaker/ModDetail.qml
- Fk/ModMaker/main.qml
- lang/zh_CN.ts
- src/ui/mod.cpp
- src/ui/mod.h
> ModMaker（鸽）

- lua/server/events/usecard.lua
- lua/server/room.lua
- packages/standard/aux_skills.lua
- packages/standard/init.lua
- packages/standard_cards/init.lua
- packages/test/init.lua
1. 谋徐盛增加大离间、复活，可以变更副将
2. 修改CardEffecting等时机的承载者
3. 修复changeHero
4. 给moveCardTo堆一个proposer
5. 修复一些标准版武将和装备
> Enchance Mouxusheng

- lua/server/ai/random_ai.lua
- lua/server/ai/smart_ai.lua
- lua/server/gamelogic.lua
- packages/standard/ai/aux_skills.lua
- packages/standard/ai/init.lua
改smart-ai... 还没改完呢，先合了
暂时不在新版本上线，还有的改的，到时候写个注释说明一下
> Smart ai （未完成）

- src/ui/qmlbackend.cpp
添加对服务器的SRV解析支持，已在WIndows11，Qt 6.6.0环境下通过测试
> :sparkles: Add resolution support for SRV

- Fk/LobbyElement/AudioSetting.qml
- Fk/LobbyElement/BGSetting.qml
- Fk/LobbyElement/RoomGeneralSettings.qml
- Fk/LobbyElement/UserInfo.qml
- Fk/Logic.js
- lua/core/debug.lua
- lua/server/events/hp.lua
- lua/server/events/usecard.lua
- lua/server/gameevent.lua
- lua/server/room.lua
- lua/server/scheduler.lua
- src/server/shell.cpp
> Enhancement2

- lua/core/skill_type/usable_skill.lua
- lua/server/events/hp.lua
- lua/server/room.lua
- packages/standard/aux_skills.lua
- packages/test/init.lua
- askForChooseCardsAndPlayers又写崩了，故修之
- 修复了Within系列没有检查to的错误
- 彻底修复了连环起点属性的bug
> 堆参数和bugfix

- lua/client/i18n/en_US.lua
- lua/client/i18n/zh_CN.lua
- lua/core/player.lua
- lua/core/skill_type/active.lua
- lua/core/skill_type/view_as.lua
- lua/server/room.lua
- packages/standard/aux_skills.lua
- packages/standard/i18n/en_US.lua
- packages/standard/i18n/zh_CN.lua
- packages/test/init.lua
- 从Utility那里搬运了askForYiji和doYiji两个函数，负责分配
虽然暂时没实现单烧条，但先这么用着
- 修复了askForCardAndPlayers的选择中可以选择复数张牌的bug
- 为prohibitDiscard添加了输入id选项
> askForYiji

- .github/workflows/docker-server.yml
- docker/Dockerfile
ci: Update Dockerfile to match Github CI.
ci: Create Docker Image Workflow.
> Server Docker Image Github CI.

- .github/workflows/docker-server.yml
ci: fix job name error
ci: add tag option for manual deployment
> Server Docker Image Github CI Fix

- src/CMakeLists.txt
- src/core/util.cpp
- src/main.cpp
- src/pch.h
- src/server/shell.cpp
- src/server/shell.h
- 修复了Log淹没正在输入命令的bug
- 增加Tab补全：命令补全、install链接推荐、用户名补全、拓展包名补全
- 为Windows端增加基于cstdio的getline函数的丐版shell
> Shell enhance

- Fk/Pages/Room.qml
- Fk/Pages/RoomLogic.js
- Fk/RoomElement/HandcardArea.qml
- src/client/client.h
- src/network/router.cpp
- src/network/router.h
- src/server/serverplayer.cpp
- src/server/serverplayer.h
- src/swig/freekill-nogui.i
- src/swig/freekill.i
- src/swig/naturalvar.i
- src/swig/server.i
- src/ui/qmlbackend.cpp
- src/ui/qmlbackend.h
> UI rewrite2

- CHANGELOG.md
- CMakeLists.txt
- Fk/Config.qml
- Fk/Pages/Room.qml
- android/AndroidManifest.xml
- 修复了确认键亮起时取消键不可用的bug
- 将版本号改成0.4.21
> okcancelfix
